### ISSUE TITLE
 I can't install Better Fps

### ISSUE THREAD

**Issue by spangelis** [Guichaguri/BetterFps#105]
* Minecraft Version: 1.8.9
* BetterFps Version: 1.2.0
* Forge/LiteLoader Version (if any): no
* Crash Logs (if any): no
* Other Mods (if any): no
---
My loader can't see versions of minecraft.
Here are screenshots
http://priscree.ru/img/a430aec62eec29.png
http://priscree.ru/img/44089f258fb99f.png
http://priscree.ru/img/67548a4dff842d.png
But on version 1.4.4 Beteer Fps and Minecraft 1.12.2 everything works.

**Comment by Guichaguri** [comment]
You need Minecraft 1.8.8 installed.
