### ISSUE TITLE
BetterFps + Fast Render

### ISSUE THREAD

**Issue by 1TapDev** [Guichaguri/BetterFps#11]
When ever you have Fast Render disabled with this mod it causes a white screen when you leave a server, leave a world. The reason I need fast render disabled is because of me using Gosu Motion which uses Minecraft Super Secret Settings and when Fast Render is on the Super Secret Settings doesnt work.

**Comment by Guichaguri** [comment]
I don't think this is still an issue, as BetterFps changed so much since Jun 2016, so I'm closing this.
Feel free to reopen if it's still an issue
