### ISSUE TITLE
Does not work on Linux

### ISSUE THREAD

**Issue by ghost** [Guichaguri/BetterFps#111]
Minecraft Version: 1.12.2
BetterFps Version: 1.4.5-1.10
Forge Version: 14.23.3.2669
Other Mods: none
OS: Ubuntu 17.10

[latest.log](https://github.com/Guichaguri/BetterFps/files/1947733/latest.log)

**Comment by Guichaguri** [comment]
It's nothing related to Linux. You're using BetterFps 1.4.5-**1.10**, which is meant to be used in Minecraft 1.10, not Minecraft 1.12.2

**Comment by ghost** [comment]
ah, you should really change the way different versions are handled
https://minecraft.curseforge.com/projects/betterfps/files/2483393
click on the upper download button and you get 1.4.5-1.10
