### ISSUE TITLE
Update Mod For 1.13

### ISSUE THREAD

**Issue by alexmercerind** [Guichaguri/BetterFps#128]
* Minecraft Version:1.13.2
* BetterFps Version: 1.4.8
* Forge/LiteLoader Version (if any): N/A
* Crash Logs (if any): 
* Other Mods (if any): Optifine
---
Update to 1.13.2.
Forge 1.13.2 is also out now.
(I am using Java math with Optifine HD, and running at 60FPS 1.12.2 on Intel Atom x5-z8300. Your mod is really helpful.)

**Comment by alexmercerind** [comment]
Please update this mod, you are the person who can make my computer run the new aquatic update. I am waiting so bad for it.

**Comment by Dimentive** [comment]
In the meantime, you should try [OptiFine](https://optifine.net).

**Comment by Guichaguri** [comment]
#131
