### ISSUE TITLE
Crashes on startup

### ISSUE THREAD

**Issue by realflow100** [Guichaguri/BetterFps#133]
* Minecraft Version: 1.12.2 Forge.
* BetterFps Version: 1.12.2 BetterFps-1.4.5-1.10.jar
* Forge/LiteLoader Version (if any): Forge 1.12.2 latest http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.5.2847/forge-1.12.2-14.23.5.2847-installer-win.exe
* Crash Logs (if any): 
[debug.log](https://github.com/Guichaguri/BetterFps/files/3639095/debug.log)
[latest.log](https://github.com/Guichaguri/BetterFps/files/3639096/latest.log)

* Other Mods (if any): None/doesnt matter
---

**Comment by Guichaguri** [comment]
1.4.5-1.10 is for Minecraft 1.10.
