### ISSUE TITLE
issues in BetterFPS installer.

### ISSUE THREAD

**Issue by eetuzi** [Guichaguri/BetterFps#135]
* Minecraft Version:
* BetterFps Version: 
* Forge/LiteLoader Version (if any): 
* Crash Logs (if any): 
* Other Mods (if any): 
---

when i was downloading BetterFPS on my pc/Minecraft there was an option ''select the version'' and i cant choose the version??? please fix this`!!!

**Comment by Guichaguri** [comment]
It only lists versions you have installed. If the version of the mod doesn't match any version you have installed, it will not show up anything.
