### ISSUE TITLE
Random algorithm messes up game

### ISSUE THREAD

**Issue by Dimentive** [Guichaguri/BetterFps#137]
My friend tried the “random” algorithm (I forgot exactly what it’s called), and it messed up his game. His player model was moving around like crazy. It looked like he was dancing. His view kept shifting all over the place too. The reason he tried this algorithm in the first place was that when he did the shift-click test, the game chose this algorithm.

### Versions
* **Minecraft:** 1.12.2
* **BetterFps:** 1.4.8 (latest)
* **Forge:** 14.23.5.2847 (latest for 1.12.2)

**Comment by Guichaguri** [comment]
That's the joke, instead of calculating correctly, it returns random values.
That's not meant to be used.
