### ISSUE TITLE
Issue with using JourneyMap (Blue screen) 

### ISSUE THREAD

**Issue by Lamer217** [Guichaguri/BetterFps#141]
* Minecraft Version:1.12.2
* BetterFps Version: 1.4.8
* Forge/LiteLoader Version (if any): 14.23.5.2847
* Crash Logs (if any): None
* Other Mods (if any): [JourneyMap](https://www.curseforge.com/minecraft/mc-mods/journeymap)
---

Using any algorithm except "Vanilla" (that disables BetterFPS functionality) makes "JourneyMap" fullscreen map a completely blue screen with no visible UI.
(https://user-images.githubusercontent.com/62716818/77680218-f20c7600-6f93-11ea-9b6c-2cadbe8f8375.png)

**Comment by ChrisLTheNerd** [comment]
Do you happen to have optifine. Journey's Map going blue has happened to me when I had buildcraft with optifine. In your case it seems like you are using Industrial Craft 2 which is a very similar mod.
