### ISSUE TITLE
BetterFps 1.3.3 crashes Minecraft 1.10.2.

### ISSUE THREAD

**Issue by Zarepheth** [Guichaguri/BetterFps#15]
I suffered a crash while exploring my modded world in Minecraft 1.10.2.

Because Realistic Terrain Generation (RTG) was the first mod I saw on the stack trace, I posted the information on their project. After much trail and error experimentation, the cause of the crash was narrowed down to Better FPS v1.3.3 when running with Forge and Minecraft 1.10.2.

[https://github.com/Team-RTG/Realistic-Terrain-Generation/issues/1054](https://github.com/Team-RTG/Realistic-Terrain-Generation/issues/1054)

The original crash report is here: [https://gist.githubusercontent.com/Zarepheth/8750e5839af1396f473703e7245a09ef/raw/2a6887c3d70077a4ffb6a93d93181b88ce3c5dfa/Crash.Log](https://gist.githubusercontent.com/Zarepheth/8750e5839af1396f473703e7245a09ef/raw/2a6887c3d70077a4ffb6a93d93181b88ce3c5dfa/Crash.Log). If needed, I can post all the subsequent crash logs from my experimentation.

**Comment by Guichaguri** [comment]
BetterFps 1.3.3 is for Minecraft 1.11, not 1.10
