### ISSUE TITLE
BetterFps not showing any version

### ISSUE THREAD

**Issue by xBluemoon** [Guichaguri/BetterFps#151]
* Minecraft Version: 1.8.9
* BetterFps Version: 1.4.5-1.10
I just download BetterFps mod then open it and choose "Install" but it not showing any version for me to install 
![image_2021-01-08_121122](https://user-images.githubusercontent.com/77138377/103976935-a6395f00-51aa-11eb-8651-6091930c84c6.png)

**Comment by thanoslovesyou** [comment]
i have the same problem and im on Mac, I hope this gets fixed soon/the creator tells us what we can do

**Comment by Skynets1927** [comment]
same problem...... i have 20 fps i want to play normally......

**Comment by Guichaguri** [comment]
1.4.5-1.10 is for Minecraft 1.10, that's why no version appears.
Please, make sure the version you have downloaded matches the Minecraft version you are playing.
