### ISSUE TITLE
Can't open up GUI; Mod isn't active

### ISSUE THREAD

**Issue by callous4567** [Guichaguri/BetterFps#16]
Heya, I've got some sort of bug or issue pertaining to the mod running.

I'm currently running Forge Beta Version 1.11-13.19.0.2154 with BetterFPS-1.3.3; I am unable to open the GUI with the mod with forge installed. Optifine works fine seemingly, so Forge is simply not taking the mod for some reason.

I've attached all the logs I can muster here : https://drive.google.com/drive/folders/0BxDhqkUPGOFCMlJobklac21zc1E?usp=sharing

All help would be appreciated! -Sebastian

**Comment by Guichaguri** [comment]
The GUI changed since the latest version. Now there is a button in the Options menu.
Reopen this issue if this is not the problem ;)

**Comment by callous4567** [comment]
Thanks! ;P
