### ISSUE TITLE
No crash or major issue, but I believe java.lang.Math is faster and better than MathHelper.

### ISSUE THREAD

**Issue by davidromrell** [Guichaguri/BetterFps#161]
No crash or major issue, but I believe java.lang.Math is faster and better than MathHelper.

FD: SIN_TABLE net/minecraft/util/math/MathHelper/SIN_TABLE 
CL: MathHelper net/minecraft/util/math/MathHelper
MD: sin net/minecraft/util/math/MathHelper/sin (F)F
MD: cos net/minecraft/util/math/MathHelper/cos (F)F

**Comment by Guichaguri** [comment]
That might actually be true for some specific scenarios, that's why there is an implementation of the "Java Algorithm" you can choose. ( https://github.com/Guichaguri/BetterFps/blob/1.12/src/main/java/guichaguri/betterfps/math/JavaMath.java )
