### ISSUE TITLE
Support for Language Files

### ISSUE THREAD

**Issue by HeartyYF** [Guichaguri/BetterFps#18]
I think this may make it more popular over the world : )

**Comment by Guichaguri** [comment]
That would definitely be useful. I'll work on it ASAP :)

**Comment by Guichaguri** [comment]
Here [it](https://github.com/Guichaguri/BetterFps/blob/1.11/src/main/resources/assets/betterfps/lang/en_us.lang) is. There are more lines than I expected, but it's finally here :)

**Comment by HeartyYF** [comment]
Sorry, I didn't find this till now...
