### ISSUE TITLE
Fast Hopper doesn't seem to support Capabilities

### ISSUE THREAD

**Issue by Ellpeck** [Guichaguri/BetterFps#19]
I recently dropped the support for IInventory in my mod Actually Additions, and now I am starting to get Reports for the machines not working with hoppers - but only if the BetterFPS "Fast Hoppers" setting is enabled.
Could it be the case that your system somehow doesn't support IItemHandler Capabilities?

**Comment by Guichaguri** [comment]
Forge added a hook between updates. I thought it wouldn't be a problem, but Forge patches it first, even though BetterFps has a higher priority D:

I think the easier way to fix this is to change my patching system to something better. Using an external library such as Badiff, VCDIFF or XDelta might not be a bad idea...

**Comment by Guichaguri** [comment]
The patching system was recoded and the new update finally rolled out.
Sorry for taking two months to fix this
