### ISSUE TITLE
Crash with 1.0.1 Minecraft 1.7.10

### ISSUE THREAD

**Issue by Xen1290** [Guichaguri/BetterFps#2]

**Comment by Xen1290** [comment]
Sorry, my mistake.

**Comment by Guichaguri** [comment]
Just for preventing other people doing the same mistake, what you did wrong?

**Comment by Xen1290** [comment]
@Guichaguri I don't know why, but I put two copy of betterfps, 1.0.1 and 1.0.0. But it doesn't appear the error of duplicate mod, but that error: https://gist.github.com/Xen1290/14aecd55adbdfe361f89
And p.s. could you move the config file on config folder? I don't know but now is in minecraft folder.

**Comment by Guichaguri** [comment]
I'll probably move in the next update.
Forge didn't detected that were two copies of BetterFps because 1.0.0 was a Forge coremod and 1.0.1 is a "tweak mod" (vanilla core mods).
Thanks for the feedback.

**Comment by Xen1290** [comment]
Oh ok, thanks!
