### ISSUE TITLE
1.3.3 in 1.10.2 using CompatLayer 0.1.3 causes players to be invisible

### ISSUE THREAD

**Issue by notacompletemoron** [Guichaguri/BetterFps#20]
I don't know if you support this, let alone if it's supported globally.

I was having serious lag issues on my server and decided to update BetterFPS as I already have CompatLayer. Going to 1.3.3 from 1.3.2 causes players to be invisible to each other when using Forge 2185 and the aforementioned version of CompatLayer (https://minecraft.curseforge.com/projects/compatlayer).

...And I just saw that CompatLayer was updated. Anyway, the scenario described above does not work. No idea if you'll support it.

**Comment by Guichaguri** [comment]
Thats strange... I'll take a look at it when I get back from vacation. Thanks for reporting it

**Comment by Guichaguri** [comment]
As it's not possible to reproduce the problem anymore, I'm closing this issue. Feel free to reopen it if I'm wrong.
