### ISSUE TITLE
Store config file in config directory

### ISSUE THREAD

**Issue by SharkWipf** [Guichaguri/BetterFps#22]
BetterFps stores its config file in the installation root, rather than the "normal" config folder.
I don't know if there's any technical reason for this, but it causes extra clutter in the install folder and also makes it hard (if not impossible, depending on Curse policies) to ship different default configs with Curse modpacks. 

Some context: I'm currently facing a bug (#13) with the default algorithm and would like to change the algorithm to Riven's full algorithm for my players, as it doesn't seem to have this bug.

**Comment by Guichaguri** [comment]
Yes, it is supposed to be in the config directory.
I'll be working on fixing this and other bugs today, and hopefully I get a new update ready for the next week.

**Comment by SharkWipf** [comment]
Thanks a lot!
