### ISSUE TITLE
Closing MC after loading a world

### ISSUE THREAD

**Issue by Tom1969** [Guichaguri/BetterFps#23]
The Mod will be loaded with MC version 11.1.2, but after connecting to a multiplayer-server or loading a world or creating a new world in singleplayer the game will close without any crasherror.

If the mod is not loaded Minecraft start the World fine.

**Comment by Guichaguri** [comment]
The latest version of the mod is for Minecraft 1.11, not 11.1.2.
A new version for 11.1.2 will come out soon
