### ISSUE TITLE
Minecraft unable to launch due to InvocationTargetException

### ISSUE THREAD

**Issue by Zarepheth** [Guichaguri/BetterFps#24]
When using Forge 13.20.0.2205 with Minecraft 1.11.2, Better FPS causes a launch failure. At least, the failure stops occurring when Better FPS is removed from the 'mods' folder and recurs when added back to the 'mods' folder. However, I don't see anything in the Log or error messages to pin the problem on Better FPS - I had to individually add/remove mods to track down the cause.

[fml-client-latest.log.txt](https://github.com/Guichaguri/BetterFps/files/691284/fml-client-latest.log.txt)

**Comment by Guichaguri** [comment]
Currently, the last version only works in 1.11. A new version for 1.11.2 is coming soon :)
