### ISSUE TITLE
1.11.2 support

### ISSUE THREAD

**Issue by SuicSoft** [Guichaguri/BetterFps#26]
I tried using the 1.11 mod for 1.11.2 but the game crashes before displaying the Mojang logo

**Comment by Guichaguri** [comment]
It will come soon. I just have to finish fixing some bugs :)

**Comment by Guichaguri** [comment]
"soon"... and it took 20 days lol

Anyway, here it is: https://minecraft.curseforge.com/projects/betterfps/files/2376778
