### ISSUE TITLE
German Translation

### ISSUE THREAD

**Issue by QuImUfu** [Guichaguri/BetterFps#31]
Translated the mod to the german language, I hope i made no mistakes. 
I unfortunately couldn't test the file ingame because the latest release doesn't include the possibility to translate the mod, but it should work.
Use it if you want.
(Had to rename it to .txt for GitHub to accept it as attachment)
[de_DE.txt](https://github.com/Guichaguri/BetterFps/files/745703/de_DE.txt)

**Comment by Guichaguri** [comment]
Thank you so much!
I'll be using your translation for sure, do you have a twitter/minecraftforum/etc account to credit you?

**Comment by Guichaguri** [comment]
A new version with your translation is out: https://minecraft.curseforge.com/projects/betterfps/files/2376746

Thanks!
