### ISSUE TITLE
Not installing

### ISSUE THREAD

**Issue by WaitForever** [Guichaguri/BetterFps#32]
The newest version isn't installing. I click install and restart the launcher and the version isn't there. It is in the versions folder though

**Comment by Guichaguri** [comment]
Do you have the "target version", like vanilla 1.11 or 1.11.2 installed?

**Comment by WaitForever** [comment]
I was installing it onto 1.11.2 Optifine

**Comment by Guichaguri** [comment]
Are you using the new launcher or the old one?
Which version of OptiFine are you using?

**Comment by PedroOtavio14** [comment]
Ola instalei o better fps com o optifine 1.11.2 e quando abro o launcher nao entra no jogo . O que eu faço?

**Comment by PedroOtavio14** [comment]
Hello I installed the better fps with optifine 1.11.2 and when I open the launcher it does not enter the game. What do I do?

**Comment by Guichaguri** [comment]
@PedroOtavio14 What versions of BetterFps and OptiFine are you using? Can you send me the logs from the launcher?

**Comment by PedroOtavio14** [comment]
I'm using the
OptiFine 1.11.2 HD U B7 and BetterFps-1.3.4

**Comment by Guichaguri** [comment]
@PedroOtavio14 Optifine 1.11.2 HD U B7 is for Minecraft 1.11.2. BetterFps 1.3.4 is for Minecraft 1.11.
You should download the right mod version for the right game version.

**Comment by PedroOtavio14** [comment]
Can you pass me the link of BetterFps 1.11.2? Why can not I find it to download

**Comment by Guichaguri** [comment]
@PedroOtavio14 [Here](https://minecraft.curseforge.com/projects/betterfps/files/2380060/download). Version 1.4.1 for Minecraft 1.11.2. It's currently beta, so stuff might be unstable.
If you find any bugs, please, report them :)

**Comment by Guichaguri** [comment]
@WaitForever I'm closing this due to no response in more than a month. Feel free to reopen it.
