### ISSUE TITLE
Double Respawn

### ISSUE THREAD

**Issue by ghost** [Guichaguri/BetterFps#34]
PLEASE help. I finally found this annoying bug that which mod causes. It is better FPS. When you die, you need to press respawn button 2 times after the real respawn. for example, i died, then clicked respawn, i respawned, and respawn button comes on the screen again. it is a BIG problem for client on server. tried all options, couldn't solve this. please help. using forge 2228, minecraft 1.11.2, latest betterfps. thanks
(it took many hours to find this bug)

**Comment by Guichaguri** [comment]
I'll investigate it.
Which BetterFps version are you using?

**Comment by ghost** [comment]
the latest version ofc. 1.4.1. minecraft 1.11.2, forge 2230.
hopefully waiting for new release :(

**Comment by ghost** [comment]
still waiting for a new update that at least fixes the double respawn bug. I had to delete the mod because other clients that joining the main server from another network, can not spawn when die. my friends were always quitting the game when die, and joining again. sometimes it doesn't even work. :(

**Comment by Guichaguri** [comment]
It took a while but I finally found the bug. It was a problem with my patcher, but it's now fixed :)
I'll release a new version soon. Thanks for reporting it :D

**Comment by ghost** [comment]
oh, awesome!!!! WHEN????

**Comment by ghost** [comment]
and i wanna ask a question,  do benchmarks accurate well? it gives me the same result all the time: Vanilla Algorithm. Should i use it really?

**Comment by Guichaguri** [comment]
The new installer is still new and unstable, I don't know how well other computers handle it.
Do me a favor: try each algorithm and see if the vanilla algorithm is the one that gives you the most FPS.

**Comment by ghost** [comment]
okay, should i restart the game after changing the algorithm????

**Comment by Guichaguri** [comment]
Yes, the algorithm is injected into the game upon initialization, so you should restart every time you change the algorithm

**Comment by ghost** [comment]
Heyy when is the new update come :D We are really waiting for it.

**Comment by Guichaguri** [comment]
When it's done.
