### ISSUE TITLE
BetterFps Options button overlaps other buttons

### ISSUE THREAD

**Issue by TheRandomLabs** [Guichaguri/BetterFps#36]
It overlaps with buttons other mods add.

**Comment by Guichaguri** [comment]
Can you send a screenshot? The code is supposed to move the button when there is already other buttons, but other mods might add the button after BetterFps.

Also, which mod is overlapping the button?

**Comment by TheRandomLabs** [comment]
![image](https://cloud.githubusercontent.com/assets/16755704/23336716/f7bdfff8-fc2b-11e6-8c33-e760198445a5.png)
Mods that are overlapping: [Xaero's Minimap](http://chocolateminecraft.com/minimap.html) and [MacroKey Keybinding](https://minecraft.curseforge.com/projects/macrokey-keybinding)

**Comment by Guichaguri** [comment]
![BetterFps Options](https://i.imgur.com/1engU4J.png)
BetterFps only

![](https://i.imgur.com/PwDOO6P.png)
BetterFps + MacroKey

![](https://i.imgur.com/IQ8u1sI.png)
BetterFps + MacroKey + Xaero's Minimap

How that looks?

**Comment by TheRandomLabs** [comment]
It looks great. I can disable the Minimap Settings button anyway, so that's fine.
