### ISSUE TITLE
Buttom "BetterFPS Options" Untranslated

### ISSUE THREAD

**Issue by HeartyYF** [Guichaguri/BetterFps#41]
![d2f i_wm 5 vo8sp9qmf8](https://cloud.githubusercontent.com/assets/17660052/23575834/0c67d42c-00cf-11e7-9bfa-b1f4f7918bb7.png)
I have imported zh_cn.lang, however, this isn't translated...I don't know why.

**Comment by Guichaguri** [comment]
I forgot to add the translation to the button. Thanks for reporting it :)
