### ISSUE TITLE
BetterFPS Isn't Working

### ISSUE THREAD

**Issue by BAKUGN** [Guichaguri/BetterFps#43]
I'm using the 1.0.1 version for 1.7.10, I have the .jar file placed in the mods folder, I have Forge installed, but when I start up Minecraft and go into the Options tab, there is no "BetterFPS Options".
If it helps I'm using this mod in a modpack with FastCraft installed.

**Comment by Guichaguri** [comment]
BetterFps for 1.7.10 doesn't have the "BetterFps Options" button. You'll have to press F12 in game to open the options screen.
