### ISSUE TITLE
       Installed Mod with Curse Forge Method- Still does not work?

### ISSUE THREAD

**Issue by ExoticButter** [Guichaguri/BetterFps#45]
I did everything like you said. I dropped the mod into the folder. There were no other duplicates in that folder. Then I open up MC and make sure The BetterFPS button is in the options. It's missing. What do I do? Please help me! 

Thanks! :)

**Comment by Guichaguri** [comment]
Which versions of Minecraft, BetterFps and Forge are you using?

**Comment by ExoticButter** [comment]
I am using the BetterFPS download for 1.8.9 and forge for 1.8.9

Just checking, how do I check my version of forge?

**Comment by ExoticButter** [comment]
Oh. My Forge version is 11.15.1.1722

**Comment by Guichaguri** [comment]
BetterFps for 1.8.9 does not have a button in the options. You have to press F12 while in game to open the options screen. If this is still not the problem, feel free to reopen this issue.
