### ISSUE TITLE
                  Downloaded with Forge Method- Mod installed with no FPS improvement??

### ISSUE THREAD

**Issue by ExoticButter** [Guichaguri/BetterFps#46]
I tried all the best algorithms, yet it doesn't make a difference in the amount of FPS I get. Also, my computer isn't some fancy gaming tech, either. I thought this would help my computer but it hasn't, why?

**Comment by Guichaguri** [comment]
How are you comparing? Make sure you're not comparing vanilla with Forge + BetterFps, Forge makes the performance a bit worse.

BetterFps for MC 1.8 only has the sine & cosine algorithm, it helps but not that much, you might be in one of rare cases where it makes no difference or it makes the performance worse.

**Comment by ExoticButter** [comment]
I'm probably one of those rare cases. Of course I am :(. Every FPS mod I tried either bugs out (Optifine) or works ONLY for 1.7.10.  I will still keep your mod installed.

**Comment by Guichaguri** [comment]
As the 1.8 version of the mod is not going to be updated anymore, I'll be closing this issue.
