### ISSUE TITLE
It will not work with the forge I have, how do I uninstall? (windows 10 user)

### ISSUE THREAD

**Issue by loperads** [Guichaguri/BetterFps#47]
Quick note: I know how to delete a file, sending it to the recycle bin. It doesn't uninstall the program.

**Comment by Guichaguri** [comment]
How did you installed it? What versions (Minecraft, Forge and BetterFps) are you using? What's the problem?

**Comment by Guichaguri** [comment]
I'll be closing this issue for no response. Feel free to reopen if the issue persists :)
