### ISSUE TITLE
Do I need optifine 

### ISSUE THREAD

**Issue by kman1312** [Guichaguri/BetterFps#48]
Do i need optifine for this mod because the mod is not working for me i even pressed f12 still didnt work.
If i need optifine for this mod then im done for because believe it or not optifine is causing me to lag ( 1.8.9 HD U H7) Help me pls

**Comment by Guichaguri** [comment]
No, you don't need Optifine. Which version of the mod are you using? Are you using it with Forge? If so, which version of Forge are you using?

**Comment by kman1312** [comment]
Im using forge 1.8.9

**Comment by Guichaguri** [comment]
@kman1312 That doesn't help. Which version of BetterFps (such as 1.3.2) and which version of Forge (such as 13.20.0.2261) are you using?

**Comment by kman1312** [comment]
Im using 13.20.0.2261 and my mod version is the newest one

**Comment by Guichaguri** [comment]
@kman1312 Forge 13.20.0.2261 is for Minecraft 1.11.2, not 1.8.9

**Comment by kman1312** [comment]
Sorry I mean forge blah blah blah

**Comment by Guichaguri** [comment]
I can't help you if you don't provide enough information. I'll be closing this issue

**Comment by kman1312** [comment]
U faty get a life kid
