### ISSUE TITLE
Crash w/ LuCraft Core Mod

### ISSUE THREAD

**Issue by WenXin20** [Guichaguri/BetterFps#49]
Forge 1.10.2-2254
Better Fps v1.4.3
[LuCraft Core](https://minecraft.curseforge.com/projects/lucraft-core) v1.0.1

The game immediately crashes after pressing the play button with LuCraft, the loading screen doesn't even launch. There is no crash report, but I do have the log.
[Log](https://pastebin.com/UbrT2QA1)

Turning the option '_fastBeacon_' in the config to false does fix the crash.

**Comment by Guichaguri** [comment]
I found the problem, it's with LuCraft Core itself. I'll talk to its developer and suggest what can be changed to fix the problem. Thanks for reporting :)

**Comment by WenXin20** [comment]
Ok, thank you.
