### ISSUE TITLE
Change Config Folder

### ISSUE THREAD

**Issue by PixelmonPRO** [Guichaguri/BetterFps#52]
* Minecraft Version: 1.10.2
* BetterFps Version: Last version
* Forge/LiteLoader Version (if any): 2281
---
Good day! I use my client with the download of game files, with this architecture:
Minecraft/ServerName/config/betterfps.json
When you start a Minecraft with BetterFPS, it creates a configuration file in the root folder of Minecraft/config/betterfps.json (and I have all the configurations in Minecraft/ServerName/config/betterfps.json).
How can I change the creation of new configs? I would like to use my pre-configured settings from the server folder.
Sorry for my English :)

**Comment by Guichaguri** [comment]
What command are you using to startup the server?

**Comment by PixelmonPRO** [comment]
sh file, last sponge forge :)
`while : ; do sleep 5 && java -Xms10G -Xmx10G -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=100 -XX:+DisableExplicitGC -XX:TargetSurvivorRatio=90 -XX:G1MaxNewSizePercent=60 -XX:G1NewSizePercent=35 -XX:InitiatingHeapOccupancyPercent=20 -XX:G1MixedGCLiveThresholdPercent=50 -XX:+AggressiveOpts -XX:+AlwaysPreTouch -XX:+UseLargePagesInMetaspace -jar forge-1.10.2-12.18.3.2281-universal.jar --log-strip-color nogui; done`

**Comment by Guichaguri** [comment]
There is two things you can try:

**Add `-Duser.dir` to the JVM arguments, just after the "java" command**
So it would be something like `... && java -Duser.dir=path/to/server ...`

**Change the working directory using the `cd` command**
The full command would be:
```sh
cd ./ServerName
while : ; do sleep 5 && java -Xms10G -Xmx10G -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=100 -XX:+DisableExplicitGC -XX:TargetSurvivorRatio=90 -XX:G1MaxNewSizePercent=60 -XX:G1NewSizePercent=35 -XX:InitiatingHeapOccupancyPercent=20 -XX:G1MixedGCLiveThresholdPercent=50 -XX:+AggressiveOpts -XX:+AlwaysPreTouch -XX:+UseLargePagesInMetaspace -jar forge-1.10.2-12.18.3.2281-universal.jar --log-strip-color nogui; done
```
