### ISSUE TITLE
Fog is not disabled

### ISSUE THREAD

**Issue by curiosity-a** [Guichaguri/BetterFps#53]
* Minecraft Version: 1.10.2
* BetterFps Version: BetterFps-1.4.3-1.10.jar
* Forge/LiteLoader Version (if any): Forge 12.18.3.2254
* Other Mods: Sky Factory 3 modpack (with some mods removed, but I don't think this matters) + Bounding Box Outline

Turn off the fog. Restart Minecraft. The fog is still present.

**Comment by Guichaguri** [comment]
I think it's a problem with the config file. Can you open the BetterFps options to see if the Fog option did change?

**Comment by curiosity-a** [comment]
It did, in fact. Both in options menu and in the config itself Here's my config:

    {"algorithm":"rivens-half","updateChecker":false,"preallocateMemory":false,"fog":false,"beaconBeam":false,"fastHopper":true,"fastBeacon":true,"fastSearch":true,"asyncSearch":true}

**Comment by curiosity-a** [comment]
Removed all mods except BetterFps. No change.

**Comment by Guichaguri** [comment]
I've just tried it in Sky Factory 3, and it seems to work perfectly well. I didn't tried with Bounding Box Outline though.

Can you send me the console logs?

**Comment by curiosity-a** [comment]
Here is the log with only Forge and BetterFps present: https://pastebin.com/EtGWL0xm

**Comment by Guichaguri** [comment]
Are you sure the Fog is set to "Fast"? Can you send screenshots proving that it's not working?

Everything is working fine for me

**Comment by curiosity-a** [comment]
http://imgur.com/a/P3dM4

**Comment by curiosity-a** [comment]
Also, I was doing some more testing and noticed that with the fog option on the fog starts very close to the player. So, since you doubted it, this confirms that the option does work. Just not as intended.

**Comment by Guichaguri** [comment]
That is really strange... Unfortunately, I can't fix a bug that I can't reproduce.
I'll leave this issue open for now in case someone else has the same problem.

**Comment by Guichaguri** [comment]
Can you send all your options? (Preferably the `options.txt` file)

**Comment by curiosity-a** [comment]
Are there any other? Here's options.txt: https://pastebin.com/Eshx0HM2
Also I had particles on "Decreased" at the time of testing, but later had to switch to "Minimal". Haven't tested the fog option since then.

**Comment by Guichaguri** [comment]
The new version with the fix is [out](https://minecraft.curseforge.com/projects/betterfps/files). Sorry for taking too long D:
