### ISSUE TITLE
BetterFps prevents items on Tinkers' Construct item/drying rack from rendering

### ISSUE THREAD

**Issue by curiosity-a** [Guichaguri/BetterFps#54]
* Minecraft Version: 1.10.2
* BetterFps Version: BetterFps-1.4.3-1.10.jar
* Forge/LiteLoader Version (if any): Forge 12.18.3.2254
* Other Mods (if any): 
Mantle-1.10.2-1.1.5.jar
TConstruct-1.10.2-2.6.3.jar
---
Place an item rack or a drying rack in the world. Right click it with an item. The item doesn't show on the rack.
This bug was not present in BetterFps 1.3.2.
Config (all options are on "vanilla" setting):

    {"algorithm":"vanilla","updateChecker":false,"preallocateMemory":true,"fog":true,"beaconBeam":true,"fastHopper":false,"fastBeacon":false,"fastSearch":false,"asyncSearch":false}

**Comment by Guichaguri** [comment]
Works fine for me. How are you installing BetterFps? There is something really wrong with your setup
![](https://i.imgur.com/6IBm2ez.png)

**Comment by curiosity-a** [comment]
Just putting the jar into "mods" folder. Is this correct?

**Comment by Guichaguri** [comment]
Yes, it should've worked... I'll try to think what can be causing it.

**Comment by curiosity-a** [comment]
I apologise. This is no bug. I should have tested TC separately. This is me being inattentive and misunderstanding one of TC's options.
