### ISSUE TITLE
Crash at startup

### ISSUE THREAD

**Issue by SoldierKucha** [Guichaguri/BetterFps#57]
* Minecraft Version: 1.11.2
* BetterFps Version: 1.4.4
* Forge/LiteLoader Version (if any): 1.11.2 - 13.20.0.2296
* Crash Logs (if any): > [16:33:45] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
> [16:33:45] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
> [16:33:45] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
> [16:33:46] [main/INFO] [FML]: Forge Mod Loader version 13.20.0.2296 for Minecraft 1.11.2 loading
> [16:33:46] [main/INFO] [FML]: Java is Java HotSpot(TM) Client VM, version 1.8.0_111, running on Windows 7:x86:6.1, installed at C:\Program Files\Java\jre1.8.0_111
> [16:33:46] [main/INFO] [FML]: Loading tweaker guichaguri.betterfps.tweaker.BetterFpsTweaker from BetterFps-1.4.4-1.10.jar
> [16:33:46] [main/INFO] [FML]: Loading tweaker optifine.OptiFineForgeTweaker from OptiFine_1.11.2_HD_U_B8.jar
> [16:33:46] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
> [16:33:46] [main/INFO] [LaunchWrapper]: Loading tweak class name guichaguri.betterfps.tweaker.BetterFpsTweaker
> [16:33:46] [main/INFO] [LaunchWrapper]: Loading tweak class name optifine.OptiFineForgeTweaker
> [16:33:46] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
> [16:33:46] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
> [16:33:46] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
> [16:33:46] [main/INFO] [LaunchWrapper]: Calling tweak class optifine.OptiFineForgeTweaker
> [16:33:46] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: acceptOptions
> [16:33:46] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: injectIntoClassLoader
> [16:33:46] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:266]: OptiFine ClassTransformer
> [16:33:46] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:266]: OptiFine URL: file:/D:/MC/mods/OptiFine_1.11.2_HD_U_B8.jar
> [16:33:46] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:266]: OptiFine ZIP file: D:\MC\mods\OptiFine_1.11.2_HD_U_B8.jar
> [16:33:46] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
> [16:33:50] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
> [16:33:51] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
> [16:33:51] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
> [16:33:51] [main/INFO] [LaunchWrapper]: Calling tweak class guichaguri.betterfps.tweaker.BetterFpsTweaker
> [16:33:51] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
> [16:33:52] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
> [16:33:52] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
> [16:33:52] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: getLaunchArguments
> [16:33:52] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
> [16:33:54] [Client thread/INFO]: Setting user: Mojo
> [16:33:55] [Client thread/INFO] [BetterFps]: Patching net.minecraft.world.biome.Biome... (akf)
> [16:33:55] [Client thread/INFO] [BetterFps]: Patching net.minecraft.block.BlockSand... (aqj)
> [16:33:55] [Client thread/INFO] [BetterFps]: Patching net.minecraft.block.BlockStainedGlassPane... (aqx)
> [16:33:55] [Client thread/ERROR] [LaunchWrapper]: Unable to launch
> java.lang.reflect.InvocationTargetException
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
> 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
> Caused by: java.lang.NoClassDefFoundError: net/minecraft/block/BlockStainedGlassPane
> 	at java.lang.Class.getDeclaredFields0(Native Method) ~[?:1.8.0_111]
> 	at java.lang.Class.privateGetDeclaredFields(Unknown Source) ~[?:1.8.0_111]
> 	at java.lang.Class.getDeclaredField(Unknown Source) ~[?:1.8.0_111]
> 	at net.minecraftforge.fml.relauncher.ReflectionHelper.findField(ReflectionHelper.java:98) ~[forge-1.11.2-13.20.0.2228.jar:?]
> 	at net.minecraftforge.fml.common.registry.GameData.<init>(GameData.java:88) ~[GameData.class:?]
> 	at net.minecraftforge.fml.common.registry.GameData.<clinit>(GameData.java:70) ~[GameData.class:?]
> 	at net.minecraft.util.SoundEvent.<clinit>(SoundEvent.java:9) ~[nm.class:?]
> 	at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:490) ~[kt.class:?]
> 	at net.minecraft.client.Minecraft.<init>(Minecraft.java:342) ~[bes.class:?]
> 	at net.minecraft.client.main.Main.main(SourceFile:124) ~[Main.class:?]
> 	... 6 more
> Caused by: java.lang.ClassNotFoundException: net.minecraft.block.BlockStainedGlassPane
> 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
> 	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
> 	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
> 	at java.lang.Class.getDeclaredFields0(Native Method) ~[?:1.8.0_111]
> 	at java.lang.Class.privateGetDeclaredFields(Unknown Source) ~[?:1.8.0_111]
> 	at java.lang.Class.getDeclaredField(Unknown Source) ~[?:1.8.0_111]
> 	at net.minecraftforge.fml.relauncher.ReflectionHelper.findField(ReflectionHelper.java:98) ~[forge-1.11.2-13.20.0.2228.jar:?]
> 	at net.minecraftforge.fml.common.registry.GameData.<init>(GameData.java:88) ~[GameData.class:?]
> 	at net.minecraftforge.fml.common.registry.GameData.<clinit>(GameData.java:70) ~[GameData.class:?]
> 	at net.minecraft.util.SoundEvent.<clinit>(SoundEvent.java:9) ~[nm.class:?]
> 	at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:490) ~[kt.class:?]
> 	at net.minecraft.client.Minecraft.<init>(Minecraft.java:342) ~[bes.class:?]
> 	at net.minecraft.client.main.Main.main(SourceFile:124) ~[Main.class:?]
> 	... 6 more
> Caused by: java.lang.NoClassDefFoundError: guichaguri/betterfps/api/IFastHopper
> 	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_111]
> 	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_111]
> 	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_111]
> 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
> 	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
> 	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
> 	at java.lang.Class.getDeclaredFields0(Native Method) ~[?:1.8.0_111]
> 	at java.lang.Class.privateGetDeclaredFields(Unknown Source) ~[?:1.8.0_111]
> 	at java.lang.Class.getDeclaredField(Unknown Source) ~[?:1.8.0_111]
> 	at net.minecraftforge.fml.relauncher.ReflectionHelper.findField(ReflectionHelper.java:98) ~[forge-1.11.2-13.20.0.2228.jar:?]
> 	at net.minecraftforge.fml.common.registry.GameData.<init>(GameData.java:88) ~[GameData.class:?]
> 	at net.minecraftforge.fml.common.registry.GameData.<clinit>(GameData.java:70) ~[GameData.class:?]
> 	at net.minecraft.util.SoundEvent.<clinit>(SoundEvent.java:9) ~[nm.class:?]
> 	at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:490) ~[kt.class:?]
> 	at net.minecraft.client.Minecraft.<init>(Minecraft.java:342) ~[bes.class:?]
> 	at net.minecraft.client.main.Main.main(SourceFile:124) ~[Main.class:?]
> 	... 6 more
> Caused by: java.lang.ClassNotFoundException: guichaguri.betterfps.api.IFastHopper
> 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
> 	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
> 	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
> 	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_111]
> 	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_111]
> 	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_111]
> 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
> 	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
> 	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
> 	at java.lang.Class.getDeclaredFields0(Native Method) ~[?:1.8.0_111]
> 	at java.lang.Class.privateGetDeclaredFields(Unknown Source) ~[?:1.8.0_111]
> 	at java.lang.Class.getDeclaredField(Unknown Source) ~[?:1.8.0_111]
> 	at net.minecraftforge.fml.relauncher.ReflectionHelper.findField(ReflectionHelper.java:98) ~[forge-1.11.2-13.20.0.2228.jar:?]
> 	at net.minecraftforge.fml.common.registry.GameData.<init>(GameData.java:88) ~[GameData.class:?]
> 	at net.minecraftforge.fml.common.registry.GameData.<clinit>(GameData.java:70) ~[GameData.class:?]
> 	at net.minecraft.util.SoundEvent.<clinit>(SoundEvent.java:9) ~[nm.class:?]
> 	at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:490) ~[kt.class:?]
> 	at net.minecraft.client.Minecraft.<init>(Minecraft.java:342) ~[bes.class:?]
> 	at net.minecraft.client.main.Main.main(SourceFile:124) ~[Main.class:?]
> 	... 6 more
> Caused by: java.lang.IncompatibleClassChangeError: Implementing class
> 	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_111]
> 	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_111]
> 	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_111]
> 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
> 	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
> 	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
> 	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_111]
> 	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_111]
> 	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_111]
> 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
> 	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
> 	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
> 	at java.lang.Class.getDeclaredFields0(Native Method) ~[?:1.8.0_111]
> 	at java.lang.Class.privateGetDeclaredFields(Unknown Source) ~[?:1.8.0_111]
> 	at java.lang.Class.getDeclaredField(Unknown Source) ~[?:1.8.0_111]
> 	at net.minecraftforge.fml.relauncher.ReflectionHelper.findField(ReflectionHelper.java:98) ~[forge-1.11.2-13.20.0.2228.jar:?]
> 	at net.minecraftforge.fml.common.registry.GameData.<init>(GameData.java:88) ~[GameData.class:?]
> 	at net.minecraftforge.fml.common.registry.GameData.<clinit>(GameData.java:70) ~[GameData.class:?]
> 	at net.minecraft.util.SoundEvent.<clinit>(SoundEvent.java:9) ~[nm.class:?]
> 	at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:490) ~[kt.class:?]
> 	at net.minecraft.client.Minecraft.<init>(Minecraft.java:342) ~[bes.class:?]
> 	at net.minecraft.client.main.Main.main(SourceFile:124) ~[Main.class:?]
> 	... 6 more
> Exception in thread "Client thread" [16:33:55] [Client thread/INFO]: [STDERR]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
> [16:33:55] [Client thread/INFO]: [STDERR]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
> [16:33:55] [Client thread/INFO]: [STDERR]: 	at java.lang.SecurityManager.checkExit(Unknown Source)
> [16:33:55] [Client thread/INFO]: [STDERR]: 	at java.lang.Runtime.exit(Unknown Source)
> [16:33:55] [Client thread/INFO]: [STDERR]: 	at java.lang.System.exit(Unknown Source)
> [16:33:55] [Client thread/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
> [16:33:55] [Client thread/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
>> [NoticeWrapper] notice size: java.awt.Dimension[width=265,height=74]
>> [NoticePanel] noticeSize java.awt.Dimension[width=388,height=74]
>> [NoticePanel] size: 413 90
>> [NoticeWrapper] notice size: java.awt.Dimension[width=305,height=85]
>> [NoticePanel] noticeSize java.awt.Dimension[width=439,height=85]
>> [NoticePanel] size: 464 101
>> [VersionManager] Refreshing versions locally...
>> [L] Minecraft closed with exit code: 1 (0x1)
>> [L] Launcher stopped.
>> [VersionManager] Versions has been refreshed (28 ms)
>> [VersionManagerUI] Version list comparing disabled.
* Other Mods (if any): Optifine
---

**Comment by Guichaguri** [comment]
You're not using 1.4.4, you're using 1.4.4-1.10

1.4.4 is for Minecraft 1.11
1.4.4-1.10 is the port of 1.4.4 for Minecraft 1.10

**Comment by SoldierKucha** [comment]
sorry im stupid

**Comment by Guichaguri** [comment]
No, it's okay, a lot of people do the same mistake (I did when I used to build my own modpacks)

Also, at least you provided crash reports, minecraft version, etc. Most of the people doesn't even provide a crash report, they just say "it crashed"

**Comment by SoldierKucha** [comment]
^_^
