### ISSUE TITLE
CME when searching in creative.

### ISSUE THREAD

**Issue by Claycorp** [Guichaguri/BetterFps#58]
* Minecraft Version: 1.10.2
* BetterFps Version: 1.4.4
* Forge/LiteLoader Version (if any): 12.18.3.2281
* Crash Logs (if any): None
* Other Mods (if any): Many, Can provide if needed.
---

https://pastebin.com/J2N8pGKv

**Comment by Guichaguri** [comment]
Thanks for sending the crash report. The bug is related to the asynchronous/multithreaded creative search, you can disable it for now

**Comment by Royal-Jelly** [comment]
My bad, and will do

**Comment by ChloeDawn** [comment]
I've also experienced a similar issue, except I had a different crash. It's caused by the changes you make to the internals though, so I thought I should link it too.

**Stack trace:** https://paste.ee/p/uVVl0

To quote mezz:

```
if you use threads to modify something that can't handle it, like this list, it will often break when the next thing tries to use it, so your crash is just a normal use of the list, that happened after or during the betterfps thread
```

**Comment by Guichaguri** [comment]
Yes, he is right. It's my fault, I didn't fully test it or thought it through as I should've

**Comment by Guichaguri** [comment]
Should be fixed now. I'll be releasing a new version soon, feel free to reopen this issue if the problem persists :)

**Comment by Guichaguri** [comment]
The new version with the fix is [out](https://minecraft.curseforge.com/projects/betterfps/files). Sorry for taking too long to fix it D:
