### ISSUE TITLE
[feature] benchmarking support

### ISSUE THREAD

**Issue by draeath** [Guichaguri/BetterFps#59]
It would be quite nice if the options menu allowed the user to execute a benchmark for the algorithms. Wouldn't need to be very elaborate, perhaps just timing an arbitrary number of executions for each and displaying the average time per operation (or even more simply, just ordering them in a list relative to each other).

This would allow more accurate selection by the user without such nondeterministic methods as watching the framerate in game.

In fact, this benchmark could be executed on first use (eg if the config file is absent) and the tested best algorithm for the user suggested or defaulted.

**Comment by Guichaguri** [comment]
It already does. Just shift-click the algorithm button :)

**Comment by draeath** [comment]
Oh cool! But it doesn't seem to work very well? I seem to get a different selection each time. I don't see any log output etc with the results. Is this put anywhere visible?

**Comment by Guichaguri** [comment]
Yes, in the installer (double click the mod jar file). The benchmark is very simple and still needs some work...
