### ISSUE TITLE
Forge with mod not working plz help

### ISSUE THREAD

**Issue by kareemkhtb** [Guichaguri/BetterFps#61]
* Minecraft Version:1.8  -  1.7.10
* BetterFps Version: the release for 1.7.10  and 1.8
* Forge/LiteLoader Version (if any): 
* Crash Logs (if any): 
* Other Mods (if any): 
---
my forge works 100% i always use mods on it and it always works but with better fps mod i dont know why better fps doesnt work i tried many times with both beta and release versions and also with both 1.7.10 and 1.8 versions and it doesnt work 
when i open my forge i open mods i dont see better fps in the mods !
pss : i know how to use forge 
i tried everything (running it with and without other mods) and nothing works please help

btw i really need your mod my fps is really bad i hope you help me soon 

thnx in advance

**Comment by Guichaguri** [comment]
BetterFps will not show in the mod list due to a missing feature in Forge, but it IS working though, you can open the BetterFps options menu to see if it works.

**Comment by kareemkhtb** [comment]
I was wondering how can I open
better FPS options ?
Is it in Minecraft or something because I didn't see anything in my settings
Where is it supposed to be?

**Comment by Guichaguri** [comment]
For older versions, you have to press F12 in game
For newer versions, there's a button in the options screen

**Comment by kareemkhtb** [comment]
thnx it woked :)

2017-05-30 17:54 GMT+03:00 Guichaguri <notifications@github.com>:

**Comment by kareemkhtb** [comment]
just the last thing
on 1.8 when i press f12 i only see the algorithm nothing else
is this how it supposed to be ?
and is there any settings i can edit (enable or disable in the mod ) and if
there is how ?

2017-05-30 18:17 GMT+03:00 kareem Alkhatib <kareemkhtb@gmail.com>:

**Comment by Guichaguri** [comment]
Yes. The 1.8 version only has the algorithm, newer versions have more improvements

I'm not going to update the 1.8 version, as it is almost 2 years old now

**Comment by kareemkhtb** [comment]
i really wonder why some people are like this believe me dude 1.8 has more
players than any 1.9 version or higher
the only server that supports 1.9 or higher is cubecraft and it also has
1.8 version in it
also 1.7 is still alive till now xD

2017-05-30 19:22 GMT+03:00 Guichaguri <notifications@github.com>:

**Comment by Guichaguri** [comment]
Yeah... That's what I can't understand:

At least, mods have a reason to not update: Changes to the game might break a lot of the code of the mod
Servers don't have this reason nor any other one to stay in older versions, as it's really easy to update to a new version which usually don't require any effort due to how Bukkit/Sponge/etc works :/

**Comment by kareemkhtb** [comment]
I mean while 1.8 is the most popular version at the moment you could maybe
make a 1.8 better FPS with the new features that you have added to the
latest versions

I really would love to

About the last message I didn't mean anything like being mean or something
sorry :(

**Comment by Guichaguri** [comment]
No, you were not mean, we're just having a discussion here :)

I'll think about a 1.8 backport ;)

**Comment by kareemkhtb** [comment]
Thnx for being cooperative

I had a really cool conversation with you

And thnx for your help
