### ISSUE TITLE
[1.11.2] Trying to clear a NonnullList that has no default value to fill the list

### ISSUE THREAD

**Issue by Royal-Jelly** [Guichaguri/BetterFps#63]
I was told by a acquaintance of mine that there was alot of spam related to  betterfps spitting errors from the creative menu and that i should pass along my [log for ya to have a look at](https://paste.ee/p/v8d5C)

**Comment by Guichaguri** [comment]
This is a known bug. See #58 

For now, set the "Fast Creative Search" option to just "on" instead of "asynchronous"

**Comment by Royal-Jelly** [comment]
my bad, I kinda was in a rush there. and will do ~
