### ISSUE TITLE
Crashes when trying to launch!?

### ISSUE THREAD

**Issue by skippergamess** [Guichaguri/BetterFps#67]
* Minecraft Version: 1.12
* BetterFps Version: 1.12
* Forge/LiteLoader Version (if any): forge 1.12
* Crash Logs (if any): 
* Other Mods (if any): Optifine 1.12
---
When I click launch, it looks like it's gonna start up but then it just crashes! What do I do!?!?!

**Comment by Guichaguri** [comment]
Which Forge and Optifine versions are you using? Can you send any crash logs?

**Comment by skippergamess** [comment]
I am using Optifine and Forge 1.12.
[2017-06-20-7.log.gz](https://github.com/Guichaguri/BetterFps/files/1090218/2017-06-20-7.log.gz)

**Comment by skippergamess** [comment]
So?? What's the problem.

**Comment by Guichaguri** [comment]
It looks like it couldn't load the config properly

**Comment by skippergamess** [comment]
How can I fix this?
