### ISSUE TITLE
BetterFPS 1.8.9 not loading on Forge

### ISSUE THREAD

**Issue by koda** [Guichaguri/BetterFps#68]
* Minecraft Version: 1.8.9
* BetterFps Version: 1.2.0
* Forge/LiteLoader Version (if any): Latest
* Crash Logs (if any): No
* Other Mods (if any): Keystrokes mod V3 and Optifine 1.8.9
---
I have BetterFPS installed and when I open my minecraft i dont see it in the mods list
![image](https://user-images.githubusercontent.com/23435125/27430647-3b3f1ae4-5741-11e7-9bce-3bd4ce4cdf8d.png)
![image](https://user-images.githubusercontent.com/23435125/27430654-41215e5e-5741-11e7-8789-b9af8d4afbac.png)

Also I dont see Keystrokes mod V3 
is there a problem with my forge?

**Comment by koda** [comment]
Nvm i fixed it

**Comment by sadindianboi** [comment]
> Nvm i fixed it

How did you fix this? Sorry for the necro post but never found a solution
