### ISSUE TITLE
1.8.9 Forge (Not working)

### ISSUE THREAD

**Issue by ghost** [Guichaguri/BetterFps#69]
* Minecraft Version: 1.8.9
* BetterFps Version: 1.2.0
* Forge/LiteLoader Version (if any): 1.8.9 - 11.15.1.1722 (Recommended)
* Crash Logs (if any): None.
* Other Mods (if any): AutoTip, CPSmod, KeystrokesMod v3, MouseDelayFix-1.0, Optifine, Orange's 1.7 Animations, Orange's Simple Mods, ProjectL, ResourcePackOrganizer, ToggleChat, and Sampler.
* Issue: I installed the mod correctly, I used the 1.2.0 version of the mod, since I was on 1.8.9 of Forge, but the mod just won't work. I followed the Installation guide for the mod correctly, but when I go into my options, I just don't see the BetterFPS button in there, nor do I think it's even installed. All my other mods work, just not this one.
---

**Comment by Guichaguri** [comment]
In older versions of BetterFps, there's no button in the options screen, instead, you have to press F12 in-game
