### ISSUE TITLE
Fast inverse Square root

### ISSUE THREAD

**Issue by DesWurstes** [Guichaguri/BetterFps#70]
Link 1: https://betterexplained.com/articles/understanding-quakes-fast-inverse-square-root/

Link 2: http://h14s.p5r.org/2012/09/0x5f3759df.html

**Comment by Guichaguri** [comment]
Thanks for the suggestion, but Minecraft vanilla already uses this algorithm.

**Comment by DesWurstes** [comment]
Are you sure? See: `net.minecraft.util.math.MathHelper`

```java
    public static float sqrt(double value)
    {
        return (float)Math.sqrt(value);
    }
```

Also, please add a license to your project.

**Comment by Guichaguri** [comment]
Yes, I'm sure. See: `net.minecraft.util.math.MathHelper#fastInvSqrt`

```java
    public static double fastInvSqrt(double p_181161_0_)
    {
        double d0 = 0.5D * p_181161_0_;
        long i = Double.doubleToRawLongBits(p_181161_0_);
        i = 6910469410427058090L - (i >> 1);
        p_181161_0_ = Double.longBitsToDouble(i);
        p_181161_0_ = p_181161_0_ * (1.5D - d0 * p_181161_0_ * p_181161_0_);
        return p_181161_0_;
    }
```

The algorithm only applies to **inverse** square roots, not regular ones.

It is licensed as you can see [here](https://github.com/Guichaguri/BetterFps/blob/1.12/LICENSE).
