### ISSUE TITLE
Mod doesn't load 1.7.10

### ISSUE THREAD

**Issue by Isc4u** [Guichaguri/BetterFps#8]
I am using the 1.0.1 version for 1.7.10 on the newest forge 1.7.10 - 10.13.4.1614 and the mod simply doesn't get loaded by forge and doesn't show up in the mods tab in the main menu. When I use the 1.0.0 version it does load and show.

**Comment by Guichaguri** [comment]
As I've mentioned a few times, it does load. Now, it is a Tweaker (not a Forge Mod), and because a missing feature in Forge, it will not show in the mod list.
Press F12 in-game to see if it loads correctly
