### ISSUE TITLE
Issues while using Betterfps with Optifine

### ISSUE THREAD

**Issue by SoldierKucha** [Guichaguri/BetterFps#80]
* Minecraft Version: 1.12
* BetterFps Version: 1.4.6
* Forge/LiteLoader Version (if any): 14.21.1.2419
* Crash Logs (if any): The game crashed whilst initializing game
Error: java.lang.AbstractMethodError
* Other Mods (if any): optifine_1.12_hd_u_c2
---
* Minecraft Version: 1.12
* BetterFps Version: 1.4.6
* Forge/LiteLoader Version (if any): 14.21.1.2419
* Crash Logs (if any): The game crashed whilst initializing game
Error: java.lang.AbstractMethodError
* Other Mods (if any): optifine_1.12_hd_u_c3
---
* Minecraft Version: 1.12
* BetterFps Version: 1.4.6
* Forge/LiteLoader Version (if any): 14.21.1.2419
* Crash Logs (if any): Didn't crashed
* Other Mods (if any): optifine_1.12_hd_u_c4
This happens
![image](https://user-images.githubusercontent.com/15803655/28490821-55485848-6eec-11e7-8196-a010dbd5780a.png)

**Comment by DesWurstes** [comment]
Are you using Taylor's algorithm?

**Comment by SoldierKucha** [comment]
Yep, i was using Taylor's Algorithm. May i ask what is most effective algorithm?

**Comment by Guichaguri** [comment]
Duplicate of #62

**Comment by DesWurstes** [comment]
To choose the best algorithm for your computer, try running the benchmark.

Shift click the algorithm selection box to run the benchmark.

**Comment by SoldierKucha** [comment]
^Thanks
