### ISSUE TITLE
Curse Update Widget Broken

### ISSUE THREAD

**Issue by bookerthegeek** [Guichaguri/BetterFps#94]
* Minecraft Version: 1.12.2
* BetterFps Version: 1.4.8
* forge-1.12.2-14.23.0.2537-universal.jar 
* liteloader-1.12.2-SNAPSHOT.jar
* Crash Logs (if any): N/A
* Other Mods (if any): N/A
---
```
Could not check for updates: Server returned HTTP response code: 503 for URL: http://widget.mcf.li/mc-mods/minecraft/229876-betterfps.json
```

**Comment by Guichaguri** [comment]
There's already an issue for the widget error: https://github.com/citricsquid/widget/issues/44
