### ISSUE TITLE
Why does BetterFps ruin my JourneyMap waypoints?

### ISSUE THREAD

**Issue by ghost** [Guichaguri/BetterFps#95]
![betterfps journeymap waypoint beacons](https://user-images.githubusercontent.com/25916106/33219718-41031458-d144-11e7-9867-e35095a9a2b8.png)

They aren’t supposed to look like that.
I use BetterFps and OptiFine. This didn’t happen before I installed BetterFps. The same visual glitch occurs when I use OptiFine’s fast render feature, but that’s disabled now.

I tried setting “Beacon Beam” to “Fast” and “Fast Beacon” to “On,” but it didn’t work.

****

**Minecraft version**: 1.12.2
**Forge version**: 14.23.0.2552
**BetterFps version**: 1.4.8
**OptiFine version**: 1.12.2 HD U C6

**Comment by Guichaguri** [comment]
It's probably caused by "beacon beam" set to "fast", which removes the glowing part of it. Can you try setting it to "fancy"?

**Comment by ghost** [comment]
The same happens with beacon beam set to fancy.

**Comment by Guichaguri** [comment]
Which algorithm are you using?

**Comment by ghost** [comment]
I tried Riven’s “full” algorithm and Riven’s “half” algorithm. Both make beacons look like this.

It’s hard for me to try every single algorithm because I have to restart the game after changing it, and since I’m playing a big modpack, it takes about six minutes to launch the game.

Anyway, I’m wondering why you can change most settings in OptiFine without restarting, but you can’t in BetterFps.

**Comment by Guichaguri** [comment]
That's actually a "micro optimization" I've been doing.
Dynamically changing options can result into a little performance loss, but it's so insignificant that I've been thinking into going back to changing dynamically.

Now that I have more time to work on BetterFps, I can experiment more :)

About your issue, I'll test it later today

**Comment by ghost** [comment]
Thanks.

**Comment by ghost** [comment]
I set “beacon beam” to fancy again, and for some reason, my JourneyMap waypoints look fine now. I don’t know why, but I’m not complaining.

Anyway, I think that the dynamic changing options are a good idea.
