### ISSUE TITLE
Question to LaunchWrapper

### ISSUE THREAD

**Issue by flawnn** [Guichaguri/BetterFps#96]
Hey there,
Could you maybe give me a explanation what LaunchWrapper is? I want to learn ASM over the holidays :D

**Comment by Guichaguri** [comment]
LaunchWrapper provides a custom classloader which loads the Minecraft code. Its classloader allows you to register your own transformers, in which you can change the bytecode of any game class.

It's open source: https://github.com/Mojang/LegacyLauncher
