### ISSUE TITLE
Unable to Check for Updates Automatically (Malformed JSON)

### ISSUE THREAD

**Issue by CDAGaming** [Guichaguri/BetterFps#98]
* Minecraft Version: 1.12.2
* BetterFps Version: Latest at time of posting
* Forge/LiteLoader Version (if any): 14.23.2.2613
* Crash Logs (if any): https://hastebin.com/xiqeyucite.sql

**Comment by Graywaren** [comment]
+1

Log Error:
[21:23:01] [BetterFps Update Checker/WARN] [BetterFps]: Could not check for updates: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 2 column 2 path $

**Comment by Geroxus** [comment]
same happened to me, picked that up on my dedictaed server for playing with some friends ... it's the exact same but i'll post it anyways

`[BetterFps Update Checker/WARN] [BetterFps]: Could not check for updates: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 2 column 2 path $`

**Comment by bhi-elliot** [comment]
+1
Forge: forge-1.12.2-14.23.5.2838-universal
Sponge: spongeforge-1.12.2-2838-7.1.7-RC3900
BetterFPS: BetterFps-1.4.8
`[19:05:40] [BetterFps Update Checker/WARN] [BetterFps]: Could not check for updates: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 2 column 2 path $`

**Comment by Guichaguri** [comment]
The version server has been taken down. Disable the update checker in the config file to remove the warning logs.

**Comment by CDAGaming** [comment]
Closed as likely won't get fixed at this point.
